env:
  - CGO_ENABLED=0
before:
  hooks:
    - make test_unit
    - cp LICENCE LICENSE.txt
builds:
  - id: linux-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - "-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= "
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
  - id: darwin-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - "-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= "
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
  - id: other-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - "-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= "
    goos:
      - netbsd
      - openbsd
      - freebsd
      - windows
      - solaris
    goarch:
      - amd64
      - "386"
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
archives:
  - format: zip
    files:
      - "LICENSE.txt"

    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  use: github-native
