// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package main

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Profile *string      `mapstructure:"profile" cty:"profile" hcl:"profile"`
	Objects []FlatObject `mapstructure:"objects" cty:"objects" hcl:"objects"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"profile": &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"objects": &hcldec.BlockListSpec{TypeName: "objects", Nested: hcldec.ObjectSpec((*FlatObject)(nil).HCL2Spec())},
	}
	return s
}

// FlatObject is an auto-generated flat version of Object.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatObject struct {
	Source      *string `mapstructure:"source" cty:"source" hcl:"source"`
	Destination *string `mapstructure:"destination" cty:"destination" hcl:"destination"`
}

// FlatMapstructure returns a new FlatObject.
// FlatObject is an auto-generated flat version of Object.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Object) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatObject)
}

// HCL2Spec returns the hcl spec of a Object.
// This spec is used by HCL to read the fields of Object.
// The decoded values from this spec will then be applied to a FlatObject.
func (*FlatObject) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"source":      &hcldec.AttrSpec{Name: "source", Type: cty.String, Required: false},
		"destination": &hcldec.AttrSpec{Name: "destination", Type: cty.String, Required: false},
	}
	return s
}
